# Day 4 – Gate-Level Simulation (GLS) and Verilog Coding Practices

This document covers Gate-Level Simulation (GLS), the importance of correct sensitivity lists, blocking vs. non-blocking assignments, and a lab demonstrating a common blocking-assignment caveat.

---

## Table of Contents

- [Gate-Level Simulation (GLS)](#gate-level-simulation-gls)
- [RTL Simulation vs Gate-Level Simulation](#rtl-simulation-vs-gate-level-simulation)
- [Missing Sensitivity List](#missing-sensitivity-list)
- [Blocking vs Non-Blocking Assignments](#blocking-vs-non-blocking-assignments)
- [Why Non-Blocking Assignments are Used for Flip-Flops](#why-non-blocking-assignments-are-used-for-flip-flops)
- [Lab: Caveat of Blocking Assignments (`blocking_caveat.v`)](#lab-caveat-of-blocking-assignments-blocking_caveatv)
- [Interview Point](#interview-point)
- [Key Takeaways](#key-takeaways)

---

## Gate-Level Simulation (GLS)

Gate-Level Simulation (GLS) is performed **after logic synthesis** to verify that the synthesized gate-level netlist behaves identically to the original RTL design. Instead of using the behavioral RTL as the Design Under Test (DUT), the synthesized netlist generated by Yosys is simulated with the **same testbench** used for RTL simulation.

The purpose of GLS is to confirm that synthesis has not introduced any functional changes into the design. Since the synthesized hardware is composed of actual standard cells, GLS provides a more realistic representation of the final circuit that will be implemented in silicon.

### Why Gate-Level Simulation is Required

RTL simulation verifies functional behavior, but synthesis performs optimizations while converting RTL into logic gates — optimizations that can sometimes expose coding issues not visible during RTL simulation. GLS is performed to:

- Verify the functional correctness of the synthesized netlist.
- Ensure the same testbench produces identical outputs before and after synthesis.
- Detect simulation-synthesis mismatches.
- Verify timing behavior when propagation delays are included.
- Validate that the synthesized hardware operates as expected.

---

## RTL Simulation vs Gate-Level Simulation

| RTL Simulation | Gate-Level Simulation |
|---|---|
| Uses RTL Verilog as the Design Under Test | Uses synthesized gate-level netlist as the Design Under Test |
| Describes circuit behavior | Represents actual hardware implementation |
| Does not include gate delays | Can include propagation delays |
| Faster simulation | More accurate hardware verification |
| Used during functional verification | Used after synthesis for hardware validation |

---

## Missing Sensitivity List

An `always` block describing combinational logic should respond to **every** input that affects the output. If one or more signals are omitted from the sensitivity list, RTL simulation may not update the output correctly, even though the synthesized hardware behaves as intended.

### Incorrect Example

```verilog
always @(sel)
begin
    if (sel)
        y = i1;
    else
        y = i0;
end
```

Here, changes to `i0` or `i1` do not trigger the `always` block because only `sel` is listed in the sensitivity list. This creates a **simulation mismatch** with the actual combinational hardware.

### Correct Coding Style

```verilog
always @(*)
begin
    if (sel)
        y = i1;
    else
        y = i0;
end
```

Using `always @(*)` automatically includes every signal referenced inside the block, ensuring correct combinational behavior.

---

## Blocking vs Non-Blocking Assignments

Verilog provides two assignment operators for procedural blocks, each intended for a different type of logic.

### Blocking Assignment (`=`)

- Statements execute **sequentially**.
- The next statement waits until the current statement finishes.
- Primarily used for **combinational logic**.

```verilog
x = a | b;
d = x & c;
```

The second statement immediately uses the **updated** value of `x`.

### Non-Blocking Assignment (`<=`)

- All right-hand side expressions are evaluated **simultaneously**.
- Left-hand side variables are updated together at the **end of the time step**.
- Used for **sequential logic** such as flip-flops.

```verilog
q <= d;
```

This accurately models hardware registers that update only on a clock edge.

---

## Why Non-Blocking Assignments are Used for Flip-Flops

A flip-flop stores data only when a clock edge occurs, and all registers in hardware update **simultaneously**. Non-blocking assignments replicate this behavior by evaluating all right-hand side expressions first, then updating every register together.

Using blocking assignments inside sequential logic can introduce incorrect ordering dependencies and simulation mismatches.

---

## Lab: Caveat of Blocking Assignments (`blocking_caveat.v`)

This lab demonstrates how improper use of blocking assignments can produce **incorrect RTL simulation results**, even though the synthesized hardware behaves correctly.

### Circuit Description

The circuit consisted of two combinational stages:

1. **First stage** — generates an intermediate signal `x` using an OR gate.
2. **Second stage** — generates the final output `d` using an AND gate.

### RTL Simulation Behavior

Because blocking assignments execute sequentially, the intermediate signal can temporarily hold its **previous** value while subsequent statements are evaluated.

When both `a` and `b` changed from logic `1` to logic `0`, signal `x` should immediately become `0`. However, the next statement used the **stale** value of `x`, causing `d` to momentarily produce an incorrect output during RTL simulation.

### Gate-Level Simulation Behavior

After synthesis, the design was implemented using actual logic gates. Since hardware evaluates all combinational logic simultaneously (subject to propagation delay), `x` correctly transitioned to `0`, and the output `d` also became `0` after the delay.

**Gate-Level Simulation matched the expected hardware behavior — RTL simulation did not.**

### Key Observation

| Aspect | RTL Simulation | Gate-Level Simulation |
|---|---|---|
| Assignment execution | Sequential (blocking) | Simultaneous (real hardware) |
| Result for this circuit | Momentary incorrect output on `d` | Correct output on `d` |
| Root cause | Improper use of blocking assignments | N/A — matches actual hardware |

- RTL simulation may exhibit incorrect behavior because blocking assignments execute sequentially.
- Synthesized hardware evaluates combinational logic simultaneously.
- Gate-Level Simulation helps detect simulation-synthesis mismatches.
- Correct coding style ensures RTL behavior matches synthesized hardware.

---

## Interview Point

**Q: Why is Gate-Level Simulation required even after RTL simulation?**

**A:** RTL simulation only verifies the behavioral description of the design. During synthesis, the RTL is transformed into actual logic gates, and coding mistakes such as incorrect sensitivity lists or improper use of blocking assignments can produce different hardware behavior. Gate-Level Simulation verifies that the synthesized gate-level netlist still satisfies the intended functionality and accurately represents the final hardware implementation.

---

## Key Takeaways

- GLS validates the synthesized netlist against the same testbench used for RTL, confirming synthesis preserved functional intent.
- An incomplete sensitivity list (e.g., `always @(sel)` instead of `always @(*)`) causes RTL simulation to miss input changes, leading to mismatches with real hardware.
- Blocking assignments (`=`) suit combinational logic; non-blocking assignments (`<=`) suit sequential logic — using the wrong one causes ordering issues and simulation errors.
- The `blocking_caveat.v` lab shows how sequential evaluation of blocking assignments can produce a temporarily incorrect RTL result that GLS reveals as inconsistent with actual hardware.
- GLS is the final checkpoint that confirms RTL simulation, synthesis, and gate-level behavior all agree.

### Day 4 Checklist

- [ ] Run GLS with the same testbench used for RTL simulation.
- [ ] Use `always @(*)` for combinational blocks to avoid missing sensitivity list issues.
- [ ] Use blocking assignments (`=`) only for combinational logic.
- [ ] Use non-blocking assignments (`<=`) only for sequential logic (flip-flops).
- [ ] Cross-check RTL and GLS waveforms to catch simulation-synthesis mismatches.
